// models/Announcement.js
const { DataTypes } = require('sequelize');

module.exports = (sequelize) => {
  const Announcement = sequelize.define(
    'Announcement',
    {
      id: {
        type: DataTypes.UUID,
        defaultValue: DataTypes.UUIDV4,
        primaryKey: true,
        allowNull: false,
      },
      title: {
        type: DataTypes.STRING(255),
        allowNull: false,
        validate: { notEmpty: true, len: [1, 255] },
      },
      content: {
        type: DataTypes.TEXT,
        allowNull: false,
        validate: { notEmpty: true },
      },
      images: {
        type: DataTypes.JSON,
        defaultValue: [],
        validate: {
          isValidImagesArray(value) {
            if (value && !Array.isArray(value)) {
              throw new Error('Images must be an array');
            }
            if (value && value.length > 2) {
              throw new Error('Cannot have more than 2 images');
            }
            if (value) {
              value.forEach((url) => {
                // more permissive URL check
                try {
                  new URL(url);
                  if (!/^https?:\/\//i.test(url)) {
                    throw new Error();
                  }
                } catch {
                  throw new Error('Each image must be a valid http(s) URL');
                }
              });
            }
          },
        },
      },
      isImportant: {
        type: DataTypes.BOOLEAN,
        defaultValue: false,
        field: 'is_important',
      },
      isActive: {
        type: DataTypes.BOOLEAN,
        defaultValue: true,
        field: 'is_active',
      },
      expiresAt: {
        type: DataTypes.DATE,
        allowNull: true,
        field: 'expires_at',
      },
    },
    {
      tableName: 'announcements',
      timestamps: true,
      createdAt: 'created_at',
      updatedAt: 'updated_at',
      indexes: [
        { fields: ['is_active'] },
        { fields: ['is_important'] },
        { fields: ['expires_at'] },
        { fields: ['created_at'] },
      ],
    }
  );

  // ---------- Instance methods ----------
  Announcement.prototype.addImage = async function (imageUrl) {
    // basic URL validation (same as model validator)
    try {
      new URL(imageUrl);
      if (!/^https?:\/\//i.test(imageUrl)) throw new Error();
    } catch {
      throw new Error('Image URL must be a valid http(s) URL');
    }

    const images = Array.isArray(this.images) ? this.images : [];
    if (images.length >= 2) {
      throw new Error('Cannot add more than 2 images');
    }

    images.push(imageUrl);
    await this.update({ images });
    await this.reload(); // ensure fresh data
    return this;
  };

  Announcement.prototype.removeImage = async function (imageUrl) {
    const images = Array.isArray(this.images) ? this.images : [];
    const updated = images.filter((i) => i !== imageUrl);
    await this.update({ images: updated });
    await this.reload();
    return this;
  };

  Announcement.prototype.clearImages = async function () {
    await this.update({ images: [] });
    await this.reload();
    return this;
  };

  Announcement.prototype.isExpired = function () {
    return this.expiresAt ? new Date() > new Date(this.expiresAt) : false;
  };

  // **Removed** beforeValidate hook – UUID is generated by the DB

  return Announcement;
};